import React, { useState, useRef, useCallback } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';
import { Switch } from '@/components/ui/switch';
import { 
  Upload, 
  Video, 
  Play, 
  Pause, 
  RotateCcw, 
  Scissors, 
  Volume2, 
  VolumeX,
  Settings,
  Download,
  Eye,
  Clock,
  FileVideo,
  Zap,
  CheckCircle,
  AlertCircle,
  Loader2,
  Trash2,
  Edit3,
  Copy,
  Share,
  BarChart3,
  Captions,
  Languages,
  Wand2,
  Sparkles,
  Monitor,
  Smartphone,
  Tablet
} from 'lucide-react';
import { toast } from 'sonner';
import { useDropzone } from 'react-dropzone';

interface VideoFile {
  id: string;
  file: File;
  name: string;
  size: number;
  duration: number;
  thumbnail?: string;
  status: 'uploading' | 'processing' | 'completed' | 'error';
  progress: number;
  url?: string;
  qualities: VideoQuality[];
  captions: Caption[];
  analytics: VideoAnalytics;
}

interface VideoQuality {
  resolution: string;
  bitrate: string;
  size: number;
  url: string;
  status: 'processing' | 'completed';
}

interface Caption {
  id: string;
  language: string;
  languageName: string;
  file?: File;
  url?: string;
  autoGenerated: boolean;
  status: 'processing' | 'completed' | 'error';
}

interface VideoAnalytics {
  views: number;
  watchTime: number;
  engagement: number;
  dropOffPoints: number[];
  averageViewDuration: number;
}

interface VideoProcessingSettings {
  generateThumbnails: boolean;
  autoTranscode: boolean;
  generateCaptions: boolean;
  enableAnalytics: boolean;
  compressionLevel: 'low' | 'medium' | 'high';
  targetQualities: string[];
}

export default function VideoUploadProcessor() {
  const [videos, setVideos] = useState<VideoFile[]>([]);
  const [selectedVideo, setSelectedVideo] = useState<VideoFile | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [settings, setSettings] = useState<VideoProcessingSettings>({
    generateThumbnails: true,
    autoTranscode: true,
    generateCaptions: true,
    enableAnalytics: true,
    compressionLevel: 'medium',
    targetQualities: ['720p', '1080p']
  });
  
  const videoRef = useRef<HTMLVideoElement>(null);
  const [isPlaying, setIsPlaying] = useState(false);
  const [currentTime, setCurrentTime] = useState(0);
  const [duration, setDuration] = useState(0);

  const onDrop = useCallback((acceptedFiles: File[]) => {
    acceptedFiles.forEach((file) => {
      if (file.type.startsWith('video/')) {
        const newVideo: VideoFile = {
          id: Date.now().toString() + Math.random(),
          file,
          name: file.name,
          size: file.size,
          duration: 0,
          status: 'uploading',
          progress: 0,
          qualities: [],
          captions: [],
          analytics: {
            views: 0,
            watchTime: 0,
            engagement: 0,
            dropOffPoints: [],
            averageViewDuration: 0
          }
        };
        
        setVideos(prev => [...prev, newVideo]);
        simulateUpload(newVideo.id);
      } else {
        toast.error('Lütfen sadece video dosyaları yükleyin');
      }
    });
  }, []);

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: {
      'video/*': ['.mp4', '.mov', '.avi', '.mkv', '.webm']
    },
    maxSize: 2 * 1024 * 1024 * 1024, // 2GB
  });

  const simulateUpload = async (videoId: string) => {
    // Simulate upload progress
    for (let progress = 0; progress <= 100; progress += 10) {
      await new Promise(resolve => setTimeout(resolve, 200));
      setVideos(prev => prev.map(video => 
        video.id === videoId 
          ? { ...video, progress, status: progress === 100 ? 'processing' : 'uploading' }
          : video
      ));
    }

    // Simulate processing
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    const mockQualities: VideoQuality[] = [
      { resolution: '720p', bitrate: '2.5 Mbps', size: 150000000, url: '#', status: 'completed' },
      { resolution: '1080p', bitrate: '5 Mbps', size: 300000000, url: '#', status: 'completed' }
    ];

    const mockCaptions: Caption[] = [
      { id: '1', language: 'tr', languageName: 'Türkçe', autoGenerated: true, status: 'completed', url: '#' },
      { id: '2', language: 'en', languageName: 'English', autoGenerated: true, status: 'processing' }
    ];

    setVideos(prev => prev.map(video => 
      video.id === videoId 
        ? { 
            ...video, 
            status: 'completed', 
            progress: 100,
            duration: 1800, // 30 minutes
            thumbnail: 'https://via.placeholder.com/320x180',
            url: '#',
            qualities: mockQualities,
            captions: mockCaptions
          }
        : video
    ));

    toast.success('Video başarıyla işlendi!');
  };

  const generateAICaptions = async (videoId: string) => {
    setIsProcessing(true);
    
    // Simulate AI caption generation
    await new Promise(resolve => setTimeout(resolve, 3000));
    
    setVideos(prev => prev.map(video => 
      video.id === videoId 
        ? {
            ...video,
            captions: [
              ...video.captions,
              { 
                id: Date.now().toString(), 
                language: 'tr', 
                languageName: 'Türkçe (AI)', 
                autoGenerated: true, 
                status: 'completed',
                url: '#'
              }
            ]
          }
        : video
    ));
    
    setIsProcessing(false);
    toast.success('AI altyazı başarıyla oluşturuldu!');
  };

  const formatFileSize = (bytes: number) => {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
  };

  const formatDuration = (seconds: number) => {
    const hours = Math.floor(seconds / 3600);
    const minutes = Math.floor((seconds % 3600) / 60);
    const secs = seconds % 60;
    
    if (hours > 0) {
      return `${hours}:${minutes.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
    }
    return `${minutes}:${secs.toString().padStart(2, '0')}`;
  };

  const getStatusIcon = (status: string) => {
    switch (status) {
      case 'uploading':
        return <Loader2 className="w-4 h-4 animate-spin text-blue-500" />;
      case 'processing':
        return <Loader2 className="w-4 h-4 animate-spin text-orange-500" />;
      case 'completed':
        return <CheckCircle className="w-4 h-4 text-green-500" />;
      case 'error':
        return <AlertCircle className="w-4 h-4 text-red-500" />;
      default:
        return null;
    }
  };

  const getStatusText = (status: string) => {
    switch (status) {
      case 'uploading':
        return 'Yükleniyor';
      case 'processing':
        return 'İşleniyor';
      case 'completed':
        return 'Tamamlandı';
      case 'error':
        return 'Hata';
      default:
        return status;
    }
  };

  return (
    <div className="space-y-6">
      {/* Upload Area */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Video className="w-5 h-5" />
            Video Yükleme ve İşleme
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div
            {...getRootProps()}
            className={`border-2 border-dashed rounded-lg p-8 text-center transition-colors cursor-pointer ${
              isDragActive 
                ? 'border-primary bg-primary/5' 
                : 'border-border hover:border-primary/50'
            }`}
          >
            <input {...getInputProps()} />
            <Upload className="w-12 h-12 text-muted-foreground mx-auto mb-4" />
            {isDragActive ? (
              <p className="text-primary font-medium">Videoları buraya bırakın...</p>
            ) : (
              <div>
                <p className="text-muted-foreground mb-2">
                  Video dosyalarını sürükleyip bırakın veya seçin
                </p>
                <p className="text-sm text-muted-foreground mb-4">
                  Desteklenen formatlar: MP4, MOV, AVI, MKV, WebM (Max: 2GB)
                </p>
                <Button variant="outline">
                  <Upload className="w-4 h-4 mr-2" />
                  Dosya Seç
                </Button>
              </div>
            )}
          </div>
        </CardContent>
      </Card>

      {/* Processing Settings */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Settings className="w-5 h-5" />
            İşleme Ayarları
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            <div className="flex items-center justify-between">
              <Label htmlFor="thumbnails">Otomatik Thumbnail</Label>
              <Switch
                id="thumbnails"
                checked={settings.generateThumbnails}
                onCheckedChange={(checked) => 
                  setSettings(prev => ({ ...prev, generateThumbnails: checked }))
                }
              />
            </div>
            
            <div className="flex items-center justify-between">
              <Label htmlFor="transcode">Otomatik Transcode</Label>
              <Switch
                id="transcode"
                checked={settings.autoTranscode}
                onCheckedChange={(checked) => 
                  setSettings(prev => ({ ...prev, autoTranscode: checked }))
                }
              />
            </div>
            
            <div className="flex items-center justify-between">
              <Label htmlFor="captions">AI Altyazı</Label>
              <Switch
                id="captions"
                checked={settings.generateCaptions}
                onCheckedChange={(checked) => 
                  setSettings(prev => ({ ...prev, generateCaptions: checked }))
                }
              />
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label htmlFor="compression">Sıkıştırma Seviyesi</Label>
              <select
                id="compression"
                className="w-full p-2 border border-border rounded-md mt-1"
                value={settings.compressionLevel}
                onChange={(e) => 
                  setSettings(prev => ({ ...prev, compressionLevel: e.target.value as any }))
                }
              >
                <option value="low">Düşük (Yüksek Kalite)</option>
                <option value="medium">Orta (Dengeli)</option>
                <option value="high">Yüksek (Küçük Dosya)</option>
              </select>
            </div>

            <div>
              <Label>Hedef Kaliteler</Label>
              <div className="flex gap-2 mt-1">
                {['480p', '720p', '1080p', '4K'].map(quality => (
                  <Button
                    key={quality}
                    variant={settings.targetQualities.includes(quality) ? 'default' : 'outline'}
                    size="sm"
                    onClick={() => {
                      setSettings(prev => ({
                        ...prev,
                        targetQualities: prev.targetQualities.includes(quality)
                          ? prev.targetQualities.filter(q => q !== quality)
                          : [...prev.targetQualities, quality]
                      }));
                    }}
                  >
                    {quality}
                  </Button>
                ))}
              </div>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Video List */}
      {videos.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileVideo className="w-5 h-5" />
              Yüklenen Videolar ({videos.length})
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {videos.map((video) => (
                <div key={video.id} className="border rounded-lg p-4">
                  <div className="flex items-start gap-4">
                    {/* Thumbnail */}
                    <div className="w-32 h-18 bg-muted rounded-lg flex items-center justify-center overflow-hidden">
                      {video.thumbnail ? (
                        <img src={video.thumbnail} alt={video.name} className="w-full h-full object-cover" />
                      ) : (
                        <Video className="w-8 h-8 text-muted-foreground" />
                      )}
                    </div>

                    {/* Video Info */}
                    <div className="flex-1 space-y-2">
                      <div className="flex items-center justify-between">
                        <h4 className="font-medium truncate">{video.name}</h4>
                        <div className="flex items-center gap-2">
                          {getStatusIcon(video.status)}
                          <Badge variant="outline">
                            {getStatusText(video.status)}
                          </Badge>
                        </div>
                      </div>

                      <div className="flex items-center gap-4 text-sm text-muted-foreground">
                        <span>{formatFileSize(video.size)}</span>
                        {video.duration > 0 && (
                          <span className="flex items-center gap-1">
                            <Clock className="w-3 h-3" />
                            {formatDuration(video.duration)}
                          </span>
                        )}
                      </div>

                      {/* Progress Bar */}
                      {video.status !== 'completed' && (
                        <div className="space-y-1">
                          <Progress value={video.progress} className="h-2" />
                          <p className="text-xs text-muted-foreground">
                            {video.status === 'uploading' ? 'Yükleniyor' : 'İşleniyor'} - %{video.progress}
                          </p>
                        </div>
                      )}

                      {/* Video Details */}
                      {video.status === 'completed' && (
                        <div className="space-y-3">
                          {/* Quality Options */}
                          <div>
                            <Label className="text-xs font-medium">Mevcut Kaliteler</Label>
                            <div className="flex gap-2 mt-1">
                              {video.qualities.map((quality, index) => (
                                <Badge key={index} variant="secondary" className="text-xs">
                                  {quality.resolution} ({formatFileSize(quality.size)})
                                </Badge>
                              ))}
                            </div>
                          </div>

                          {/* Captions */}
                          <div>
                            <div className="flex items-center justify-between">
                              <Label className="text-xs font-medium">Altyazılar</Label>
                              <Button
                                variant="outline"
                                size="sm"
                                onClick={() => generateAICaptions(video.id)}
                                disabled={isProcessing}
                              >
                                <Wand2 className="w-3 h-3 mr-1" />
                                AI Altyazı
                              </Button>
                            </div>
                            <div className="flex gap-2 mt-1">
                              {video.captions.map((caption) => (
                                <Badge 
                                  key={caption.id} 
                                  variant={caption.status === 'completed' ? 'default' : 'secondary'}
                                  className="text-xs"
                                >
                                  {caption.languageName}
                                  {caption.autoGenerated && ' (AI)'}
                                </Badge>
                              ))}
                            </div>
                          </div>

                          {/* Actions */}
                          <div className="flex gap-2">
                            <Button variant="outline" size="sm">
                              <Play className="w-3 h-3 mr-1" />
                              Önizle
                            </Button>
                            <Button variant="outline" size="sm">
                              <Edit3 className="w-3 h-3 mr-1" />
                              Düzenle
                            </Button>
                            <Button variant="outline" size="sm">
                              <BarChart3 className="w-3 h-3 mr-1" />
                              Analitik
                            </Button>
                            <Button variant="outline" size="sm">
                              <Download className="w-3 h-3 mr-1" />
                              İndir
                            </Button>
                            <Button variant="outline" size="sm">
                              <Share className="w-3 h-3 mr-1" />
                              Paylaş
                            </Button>
                            <Button variant="outline" size="sm">
                              <Trash2 className="w-3 h-3 text-destructive" />
                            </Button>
                          </div>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Video Analytics */}
      {videos.some(v => v.status === 'completed') && (
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <BarChart3 className="w-5 h-5" />
              Video Analitikleri
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="text-center p-4 bg-muted/30 rounded-lg">
                <div className="text-2xl font-bold text-primary">
                  {videos.reduce((total, video) => total + video.analytics.views, 0)}
                </div>
                <div className="text-sm text-muted-foreground">Toplam İzlenme</div>
              </div>
              
              <div className="text-center p-4 bg-muted/30 rounded-lg">
                <div className="text-2xl font-bold text-green-600">
                  {Math.round(videos.reduce((total, video) => total + video.analytics.watchTime, 0) / 60)}dk
                </div>
                <div className="text-sm text-muted-foreground">İzlenme Süresi</div>
              </div>
              
              <div className="text-center p-4 bg-muted/30 rounded-lg">
                <div className="text-2xl font-bold text-orange-600">
                  %{Math.round(videos.reduce((total, video) => total + video.analytics.engagement, 0) / videos.length)}
                </div>
                <div className="text-sm text-muted-foreground">Etkileşim Oranı</div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}
    </div>
  );
}
